import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dir } from "i18next";
import TranslationsProvider from "@/i18n/client-provider";
import { useTranslation } from "@/i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}>) {
  const defaultNS = "common";
  const { lng } = await params;

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { i18n } = await useTranslation(lng, defaultNS);
  const resources = i18n.services.resourceStore.data;

  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TranslationsProvider lng={lng} ns={defaultNS} resources={resources}>
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
